### ISSUE TITLE
백기선 자바 스터디 2주차 - 지원 질문

### ISSUE THREAD

**Issue by jiwon709** [effectiveJava-study/java-study#2]
@chanhong-dev 
변수 초기화 방법 중 초기화 블럭에서
클래스 초기화 블럭 에서 JVM이 클래스 로더로 로딩 시점에 초기화를 진행한다 했는데
class 접근 범위도 구분해서 진행되나요? .class 이기만 하면 일단 무조건 다 진행되는 건가요 ?

**Comment by jiwon709** [comment]
@Ohjinn
1차 및 2차 배열 선언하기 에서
2차원 배열은 1차원 배열과 같이 heap 요소에 할당하지만,
1차원에는 2차원 배열의 주솟값이 들어가게 된다라는게

[2차원 배열의 주솟값][int 타입 크기의 요소] --> heap 요소에 할당

이 뜻인가요 ..? ?????

**Comment by Ohjinn** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/67143721/175801029-ad203356-fc49-4333-959f-192453a0ce18.png">
첫번째 출처 노션의 사진 보면 이해될것 같아요!
